# This is a basic workflow to help you get started with Actions

name: Simple-Flask-App
env:
  APPLICATION_NAME: "Simple-Flask-App"
  PACKAGE         : "flask-app-ver-${{github.sha}}"

on:
  push:
    branches: [ main ]

jobs:

  deploy:

    runs-on: ubuntu-latest
    
    steps:
      - name: Run a one-line script
        run: echo Hello, world!; echo env1
      
      - name: Some executable commands
        run: |
          echo "Comm 1"
          echo "Comm 2"
          echo "Env 1 value ${{ env.APPLICATION_NAME}}"
          echo "Env 2 value ${{ env.PACKAGE}}"
          
      - name: List working dir
        run: ls -la
      
      - name: Clone git repo
        uses: actions/checkout@v1
        
      - name: List working dir after clone
        run: ls -la

      - name: Check some utils 1
        run: zip

      - name: Check some utils 2
        run: python -V; python3 -V
